// src/main/ui/src/views/ReportsList.vue
<template>
  <div class="row">
    <div class="col-12">
      <h1>{{ $t('term.balanceByClient') }}</h1>

      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">{{ $t('term.client') }}</th>
            <th scope="col">{{ $t('term.total') }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in reports.balanceByClient" :key="item.clientName">
            <td>{{item.clientName}}</td>
            <td>{{item.totalFormatted}}$</td>
          </tr>
        </tbody>
      </table>

      <p>{{ $t('term.globalBalance') }}: {{reports.globalBalanceFormatted}}$</p>

      <h1>{{ $t('term.itemsByCategory') }}</h1>

      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">{{ $t('term.date') }}</th>
            <th scope="col">{{ $t('term.category') }}</th>
            <th scope="col">{{ $t('term.total') }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in reports.itemsByCategory" :key="item.monthDate + '-' + item.category">
            <td>{{item.monthDate}}</td>
            <td>{{item.category}}</td>
            <td>{{item.totalFormatted}}$</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import http from '@/utils/http'

export default {
  name: 'ReportsList',
  data() {
    return {
      reports: {}
    }
  },
  methods: {
    refresh() {
      console.log('Reports - Load')
      http.get('/api/report')
        .then(response => {
          this.reports = response.data.item || {}
        })
        .catch(error => {
          console.error('Error loading reports', error)
          this.reports = {}
        })
    }
  },
  mounted() {
    this.refresh()
  }
}
</script>

<style scoped>
</style>

// src/main/ui/src/views/ReportsList.jsx
import React, {useEffect, useState} from 'react'
import service from '../service'
import {t} from '../utils/TranslationUtils'

function ReportsList() {
    const [reports, setReports] = useState({})

    // Function to refresh reports
    const refresh = async () => {
        console.log('Reports - Load')

        try {
            const response = await service.reportGet()
            setReports(response.data.item || {})
        } catch (error) {
            console.error('Error loading reports', error)
            setReports({})
        }
    }

    // Initial load
    useEffect(() => {
        refresh()
    }, [])

    return (
        <div className="row">
            <div className="col-12">
                <h1>{t('term.balanceByClient')}</h1>

                <table className="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">{t('term.client')}</th>
                        <th scope="col">{t('term.total')}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {reports.balanceByClient && reports.balanceByClient.map(item => (
                        <tr key={item.clientName}>
                            <td>{item.clientName}</td>
                            <td>{item.totalFormatted}$</td>
                        </tr>
                    ))}
                    </tbody>
                </table>

                <p>{t('term.globalBalance')}: {reports.globalBalanceFormatted}$</p>

                <h1>{t('term.itemsByCategory')}</h1>

                <table className="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">{t('term.date')}</th>
                        <th scope="col">{t('term.category')}</th>
                        <th scope="col">{t('term.total')}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {reports.itemsByCategory && reports.itemsByCategory.map(item => (
                        <tr key={`${item.monthDate}-${item.category}`}>
                            <td>{item.monthDate}</td>
                            <td>{item.category}</td>
                            <td>{item.totalFormatted}$</td>
                        </tr>
                    ))}
                    </tbody>
                </table>
            </div>
        </div>
    )
}

export default ReportsList
