// src/main/ui/src/views/TechnicalSupportsList.vue
<template>
  <div class="row">
    <div class="col-12">
      <button type="button" class="btn btn-success" data-bs-toggle="modal" @click="showCreate()" data-bs-target="#createModal">{{ $t('button.create') }}</button>

      <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="createModalLabel">{{ $t('button.create') }}</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <error-results :formResult="formResult"></error-results>

              <div class="mb-3">
                <label for="sid">{{ $t('term.sid') }}</label> <input type="text" class="form-control" id="sid" v-model="createForm.sid" autocomplete="off">
                <div class="text-danger" v-if="formResult.validationErrorsByField && formResult.validationErrorsByField.sid">
                  <p v-for="errorCode in formResult.validationErrorsByField.sid" :key="errorCode">{{ $t(errorCode) }}</p>
                </div>
              </div>

              <div class="mb-3">
                <label for="pricePerHour">{{ $t('term.pricePerHour') }}</label> <input type="text" class="form-control" id="pricePerHour" v-model="createForm.pricePerHour" autocomplete="off">
                <div class="text-danger" v-if="formResult.validationErrorsByField && formResult.validationErrorsByField.pricePerHour">
                  <p v-for="errorCode in formResult.validationErrorsByField.pricePerHour" :key="errorCode">{{ $t(errorCode) }}</p>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ $t('button.close') }}</button>
              <button type="button" class="btn btn-success" @click="create()">{{ $t('button.create') }}</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="editModalLabel">{{ $t('button.edit') }}</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <error-results :formResult="formResult"></error-results>

              <div class="mb-3">
                <label for="sid2">{{ $t('term.sid') }}</label> <input type="text" class="form-control" id="sid2" v-model="editForm.sid" autocomplete="off">
                <div class="text-danger" v-if="formResult.validationErrorsByField && formResult.validationErrorsByField.sid">
                  <p v-for="errorCode in formResult.validationErrorsByField.sid" :key="errorCode">{{ $t(errorCode) }}</p>
                </div>
              </div>

              <div class="mb-3">
                <label for="pricePerHour2">{{ $t('term.pricePerHour') }}</label> <input type="text" class="form-control" id="pricePerHour2" v-model="editForm.pricePerHour" autocomplete="off">
                <div class="text-danger" v-if="formResult.validationErrorsByField && formResult.validationErrorsByField.pricePerHour">
                  <p v-for="errorCode in formResult.validationErrorsByField.pricePerHour" :key="errorCode">{{ $t(errorCode) }}</p>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ $t('button.close') }}</button>
              <button type="button" class="btn btn-success" @click="edit()">{{ $t('button.edit') }}</button>
            </div>
          </div>
        </div>
      </div>

      <pagination class="float-end" :pagination="pagination" @changePage="refresh($event.pageId)"></pagination>

      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">{{ $t('term.sid') }}</th>
            <th scope="col">{{ $t('term.pricePerHour') }}</th>
            <th scope="col">{{ $t('term.actions') }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in items" :key="item.sid">
            <td>{{item.sid}}</td>
            <td>{{item.pricePerHourFormatted}}$</td>
            <td>
              <div>
                <button class="btn btn-sm btn-primary" data-bs-toggle="modal" @click="showEdit(item)" data-bs-target="#editModal">{{ $t('button.edit') }}</button>
                <button class="btn btn-sm btn-danger" @click="deleteOne(item)">{{ $t('button.delete') }}</button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import ErrorResults from '@/components/ErrorResults.vue'
import Pagination from '@/components/Pagination.vue'
import http from '@/utils/http'
import { priceToLong } from '@/utils/features'

export default {
  name: 'TechnicalSupportsList',
  components: {
    ErrorResults,
    Pagination
  },
  data() {
    return {
      queries: {},
      items: [],
      pagination: {
        currentPageUi: 1,
        totalPages: 1,
        firstPage: true,
        lastPage: true,
      },
      createForm: {},
      editForm: {},
      formResult: {},
    }
  },
  methods: {
    refresh(pageId) {
      if (pageId === undefined) {
        pageId = 1
      }
      this.queries.pageId = pageId
      console.log('Technical Supports - Load', this.queries)

      http.get('/api/technicalSupport/listAll', this.queries)
        .then(response => {
          this.pagination = response.data.pagination
          this.items = response.data.items || []
        })
        .catch(error => {
          console.error('Error loading technical supports', error)
          this.items = []
        })
    },
    showCreate() {
      this.formResult = {}
    },
    create() {
      this.formResult = {}
      const clonedForm = JSON.parse(JSON.stringify(this.createForm))
      clonedForm.pricePerHour = priceToLong(clonedForm.pricePerHour)
      console.log('Technical Support - Create', clonedForm)

      http.post('/api/technicalSupport', clonedForm)
        .then(response => {
          this.formResult = response.data
          if (response.data.success) {
            document.querySelector('#createModal .btn-secondary').click()
            http.showSuccess(this.$t('prompt.create.success', [this.createForm.sid]))
            this.refresh(this.queries.pageId)
          }
        })
        .catch(error => {
          console.error('Error creating technical support', error)
        })
    },
    deleteOne(item) {
      if (confirm(this.$t('prompt.delete.confirm', [item.sid]))) {
        console.log('Technical Support - Delete', item.sid)

        http.delete('/api/technicalSupport/' + item.sid)
          .then(() => {
            http.showSuccess(this.$t('prompt.delete.success', [item.sid]))
            this.refresh(this.queries.pageId)
          })
          .catch(error => {
            console.error('Error deleting technical support', error)
          })
      }
    },
    showEdit(item) {
      this.formResult = {}
      Object.assign(this.editForm, item)
      this.editForm.id = item.sid
      this.editForm.pricePerHour = this.editForm.pricePerHourFormatted
    },
    edit() {
      this.formResult = {}
      const clonedForm = JSON.parse(JSON.stringify(this.editForm))
      clonedForm.pricePerHour = priceToLong(clonedForm.pricePerHour)
      console.log('Technical Support - Edit', clonedForm)

      http.put('/api/technicalSupport/' + clonedForm.id, clonedForm)
        .then(response => {
          this.formResult = response.data
          if (response.data.success) {
            document.querySelector('#editModal .btn-secondary').click()
            http.showSuccess(this.$t('prompt.edit.success', [this.editForm.sid]))
            this.refresh(this.queries.pageId)
          }
        })
        .catch(error => {
          console.error('Error editing technical support', error)
        })
    },
  },
  mounted() {
    this.refresh()
  }
}
</script>

<style scoped>
</style>

// src/main/ui/src/views/TechnicalSupportsList.jsx
import React, {useEffect, useState} from 'react'
import ErrorResults from '../components/ErrorResults'
import PaginationControl from '../components/PaginationControl'
import service, {showSuccess} from '../service'
import {priceToLong} from '../utils/features'
import {t} from '../utils/TranslationUtils'

function TechnicalSupportsList() {
    const [queries, setQueries] = useState({})
    const [items, setItems] = useState([])
    const [pagination, setPagination] = useState({
        currentPageUi: 1,
        totalPages: 1,
        firstPage: true,
        lastPage: true,
    })
    const [createForm, setCreateForm] = useState({})
    const [editForm, setEditForm] = useState({})
    const [formResult, setFormResult] = useState({})

    // Function to refresh the list of technical supports
    const refresh = async (pageId) => {
        if (pageId === undefined) {
            pageId = 1
        }

        setQueries(prev => ({
            ...prev,
            pageId
        }))

        console.log('Technical Supports - Load', {pageId})

        try {
            const response = await service.technicalSupportListAll(pageId)
            setPagination(response.data.pagination)
            setItems(response.data.items || [])
        } catch (error) {
            console.error('Error loading technical supports', error)
            setItems([])
        }
    }

    // Function to show create modal
    const showCreate = () => {
        setFormResult({})
    }

    // Function to create a new technical support
    const create = async () => {
        setFormResult({})
        const clonedForm = JSON.parse(JSON.stringify(createForm))
        clonedForm.pricePerHour = priceToLong(clonedForm.pricePerHour)
        console.log('Technical Support - Create', clonedForm)

        try {
            const response = await service.technicalSupportCreate(clonedForm)
            setFormResult(response.data)
            if (response.data.success) {
                document.querySelector('#createModal .btn-secondary').click()
                showSuccess(`Successfully created ${createForm.sid}`)
                refresh(queries.pageId)
            }
        } catch (error) {
            console.error('Error creating technical support', error)
        }
    }

    // Function to delete a technical support
    const deleteOne = async (item) => {
        if (window.confirm(`Are you sure you want to delete ${item.sid}?`)) {
            console.log('Technical Support - Delete', item.sid)

            try {
                await service.technicalSupportDelete(item.sid)
                showSuccess(`Successfully deleted ${item.sid}`)
                refresh(queries.pageId)
            } catch (error) {
                console.error('Error deleting technical support', error)
            }
        }
    }

    // Function to show edit modal
    const showEdit = (item) => {
        setFormResult({})
        setEditForm({
            ...item,
            id: item.sid,
            pricePerHour: item.pricePerHourFormatted
        })
    }

    // Function to edit a technical support
    const edit = async () => {
        setFormResult({})
        const clonedForm = JSON.parse(JSON.stringify(editForm))
        clonedForm.pricePerHour = priceToLong(clonedForm.pricePerHour)
        console.log('Technical Support - Edit', clonedForm)

        try {
            const response = await service.technicalSupportUpdate(clonedForm.id, clonedForm)
            setFormResult(response.data)
            if (response.data.success) {
                document.querySelector('#editModal .btn-secondary').click()
                showSuccess(`Successfully edited ${editForm.sid}`)
                refresh(queries.pageId)
            }
        } catch (error) {
            console.error('Error editing technical support', error)
        }
    }

    // Function to handle create form field changes
    const handleCreateFormChange = (field, value) => {
        setCreateForm(prev => ({
            ...prev,
            [field]: value
        }))
    }

    // Function to handle edit form field changes
    const handleEditFormChange = (field, value) => {
        setEditForm(prev => ({
            ...prev,
            [field]: value
        }))
    }

    // Initial load
    useEffect(() => {
        refresh()
    }, [])

    return (
        <div className="row">
            <div className="col-12">
                <button type="button" className="btn btn-success" data-bs-toggle="modal" onClick={showCreate}
                        data-bs-target="#createModal">{t('button.create')}</button>

                <div className="modal fade" id="createModal" tabIndex="-1" role="dialog"
                     aria-labelledby="createModalLabel" aria-hidden="true">
                    <div className="modal-dialog" role="document">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title" id="createModalLabel">{t('button.create')}</h5>
                                <button type="button" className="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div className="modal-body">
                                <ErrorResults formResult={formResult}/>

                                <div className="mb-3">
                                    <label htmlFor="sid">{t('term.sid')}</label>
                                    <input
                                        type="text"
                                        className="form-control"
                                        id="sid"
                                        value={createForm.sid || ''}
                                        onChange={(e) => handleCreateFormChange('sid', e.target.value)}
                                        autoComplete="off"
                                    />
                                    {formResult.validationErrorsByField && formResult.validationErrorsByField.sid && (
                                        <div className="text-danger">
                                            {formResult.validationErrorsByField.sid.map((errorCode, index) => (
                                                <p key={index}>{t(errorCode)}</p>
                                            ))}
                                        </div>
                                    )}
                                </div>

                                <div className="mb-3">
                                    <label htmlFor="pricePerHour">{t('term.pricePerHour')}</label>
                                    <input
                                        type="text"
                                        className="form-control"
                                        id="pricePerHour"
                                        value={createForm.pricePerHour || ''}
                                        onChange={(e) => handleCreateFormChange('pricePerHour', e.target.value)}
                                        autoComplete="off"
                                    />
                                    {formResult.validationErrorsByField && formResult.validationErrorsByField.pricePerHour && (
                                        <div className="text-danger">
                                            {formResult.validationErrorsByField.pricePerHour.map((errorCode, index) => (
                                                <p key={index}>{t(errorCode)}</p>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            </div>
                            <div className="modal-footer">
                                <button type="button" className="btn btn-secondary"
                                        data-bs-dismiss="modal">{t('button.close')}</button>
                                <button type="button" className="btn btn-success"
                                        onClick={create}>{t('button.create')}</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="modal fade" id="editModal" tabIndex="-1" role="dialog" aria-labelledby="editModalLabel"
                     aria-hidden="true">
                    <div className="modal-dialog" role="document">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title" id="editModalLabel">{t('button.edit')}</h5>
                                <button type="button" className="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div className="modal-body">
                                <ErrorResults formResult={formResult}/>

                                <div className="mb-3">
                                    <label htmlFor="sid2">{t('term.sid')}</label>
                                    <input
                                        type="text"
                                        className="form-control"
                                        id="sid2"
                                        value={editForm.sid || ''}
                                        onChange={(e) => handleEditFormChange('sid', e.target.value)}
                                        autoComplete="off"
                                    />
                                    {formResult.validationErrorsByField && formResult.validationErrorsByField.sid && (
                                        <div className="text-danger">
                                            {formResult.validationErrorsByField.sid.map((errorCode, index) => (
                                                <p key={index}>{t(errorCode)}</p>
                                            ))}
                                        </div>
                                    )}
                                </div>

                                <div className="mb-3">
                                    <label htmlFor="pricePerHour2">{t('term.pricePerHour')}</label>
                                    <input
                                        type="text"
                                        className="form-control"
                                        id="pricePerHour2"
                                        value={editForm.pricePerHour || ''}
                                        onChange={(e) => handleEditFormChange('pricePerHour', e.target.value)}
                                        autoComplete="off"
                                    />
                                    {formResult.validationErrorsByField && formResult.validationErrorsByField.pricePerHour && (
                                        <div className="text-danger">
                                            {formResult.validationErrorsByField.pricePerHour.map((errorCode, index) => (
                                                <p key={index}>{t(errorCode)}</p>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            </div>
                            <div className="modal-footer">
                                <button type="button" className="btn btn-secondary"
                                        data-bs-dismiss="modal">{t('button.close')}</button>
                                <button type="button" className="btn btn-success"
                                        onClick={edit}>{t('button.edit')}</button>
                            </div>
                        </div>
                    </div>
                </div>

                <PaginationControl className="float-end" state={pagination}
                            onPageChange={(newPageId) => refresh(newPageId)}/>

                <table className="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">{t('term.sid')}</th>
                        <th scope="col">{t('term.pricePerHour')}</th>
                        <th scope="col">{t('term.actions')}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {items.map(item => (
                        <tr key={item.sid}>
                            <td>{item.sid}</td>
                            <td>{item.pricePerHourFormatted}$</td>
                            <td>
                                <div>
                                    <button className="btn btn-sm btn-primary" data-bs-toggle="modal"
                                            onClick={() => showEdit(item)}
                                            data-bs-target="#editModal">{t('button.edit')}</button>
                                    <button className="btn btn-sm btn-danger"
                                            onClick={() => deleteOne(item)}>{t('button.delete')}</button>
                                </div>
                            </td>
                        </tr>
                    ))}
                    </tbody>
                </table>
            </div>
        </div>
    )
}

export default TechnicalSupportsList
